name: Linting
on: push

jobs:


  Linting:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: actions/setup-node@v4

      - name: Install redocly/cli
        run: npm i -g @redocly/cli@latest

      - name: Run Linting Rules
        run: redocly lint ./src/openAPI.yaml
