name: Linting
on: push

jobs:


  Linting:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Setup Environment
        uses: actions/setup-node@v4

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Run Linting Rules
        run: exec lint

